# Generated by Django 5.2 on 2025-05-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alphabot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='text',
        ),
    ]
