# Generated by Django 5.2 on 2025-05-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphabot', '0002_rename_content_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_type',
            field=models.CharField(default='chat', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=20),
        ),
    ]
